### PR TITLE
Multipass: improve category landing pages

### PR DESCRIPTION
**Pull request by nielsenjared**
Hey @rkratky ! 
Here's a first pass at the how-to landing page. Let me know if I'm on track and I'll proceed with the other three. 

You'll notice I left a few TODOs in place of the lists of links. How are links rendered? Do I need to add them? If so, is the syntax standard Markdown. Or does the template engine insert them? If so, is there a variable I need to insert?

### CODE REVIEW

**Comment by rkratky** [comment]
@nielsenjared, this is really good, thanks! Feel free to suggest content for the other landing pages in this manner.

(The lists of links are generated automatically, so no need to use placeholders for them.)

**Comment by townsend2010** [comment]
Hi @nielsenjared!

This is really great!  I'm currently working on improving the landing pages, this is exactly what I need. :smiley: I can apply your changes here to the Discourse docs if you are ready.

Also, as @rkratky pointed out, please feel free to contribute to the other landing pages as well.

**Comment by townsend2010** [comment]
Hi @nielsenjared!  I've applied these changes to our Discourse docs.  Thank you so much for your contribution!

**Comment by townsend2010** [comment]
Hi @rkratky,

I've applied the changes here to Discourse.  I'm not sure how this is supposed to be closed.  Thanks!

**Comment by rkratky** [comment]
Thanks @townsend2010. I'll handle it next week.

**Pull request closed without merging**
